version: "3"
services:
  mslave:
    container_name: mslave
    image: registry.roleit.com:5443/mongo:5.0.15-focal
    restart: always
    volumes:
      - /rit/smongo/2role/db:/data/db:rw
    env_file:
      /rit/smongo/mongod.env
    ports:
      - 27020:27017
    command: 'mongod --replSet reprit --auth --keyFile /dcs/mongodb-keyfile'
    # healthcheck:
    #   test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 2

  arbiter:
    container_name: arbiter
    image: registry.roleit.com:5443/mongo:5.0.15-focal
    restart: always
    # volumes:
    #   - /rit/smongo/2role/db:/data/db:rw
    env_file:
      /rit/smongo/mongod.env
    ports:
      - 27021:27017
    command: 'mongod --replSet reprit --auth --keyFile /dcs/mongodb-keyfile'