version: "3.8"

services:
  # app:
  #   image: node
  #   container_name: linksweb
  #   restart: on-failure:3
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_HOST=db
  #     - DATABASE_USER=fazt
  #     - DATABASE_PASSWORD=mypassword
  #     - DATABASE_NAME=linksdb
  #   volumes:
  #     - .:/app
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   command: bash -c "npm install && npm run dev"
  db:
    image: mysql
    container_name: ms
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=dcs
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /d/extra/mysql/nodejs-mysql-links/database/db.sql:/docker-entrypoint-initdb.d/db.sql
