version: '3'
services: 
  haproxy: 
    image: haproxy:2.3
    user: root
    container_name: haproxy 
    restart: always 
    volumes: 
      - /rit/atway/haproxy:/usr/local/etc/haproxy:rw
    network_mode: "host"
    # depends_on:
      # - redis
