version: '3'
services:

  ## Config Servers
  configsvr01:
    image: registry.roleit.com:5443/mongo:5.0.15-focal
    container_name: mongo-config-01
    command: mongod --port 27017 --configsvr --replSet rs-config-server --keyFile /dcs/mongodb-keyfile
    volumes:
      - /rit/smongo/1role/scripts:/scripts:ro
      - /rit/smongo/1role/configsvr_1_data/db:/data/db:rw
      - /rit/smongo/1role/configsvr_1_data/configdb:/data/configdb:rw
    ports:
      - 27119:27017
    restart: always
    # healthcheck:
    #   test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5


  ## Shards 01
  shard01-a:
    image: registry.roleit.com:5443/mongo:5.0.15-focal
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --keyFile /dcs/mongodb-keyfile
    volumes:
      - /rit/smongo/1role/scripts:/scripts:ro
      - /rit/smongo/1role/shard01_1_data/db:/data/db:rw
      - /rit/smongo/1role/shard01_1_data/configdb:/data/configdb:rw
    ports:
      - 27122:27017
    restart: always
    # healthcheck:
    #   test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5

  ## Shards 02
  shard02-a:
    image: registry.roleit.com:5443/mongo:5.0.15-focal
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --keyFile /dcs/mongodb-keyfile
    volumes:
      - /rit/smongo/1role/scripts:/scripts:ro
      - /rit/smongo/1role/shard02_1_data/db:/data/db:rw
      - /rit/smongo/1role/shard02_1_data/configdb:/data/configdb:rw
    ports:
      - 27125:27017
    restart: always
    # healthcheck:
    #   test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5

  ## Router
  router01:
    image: registry.roleit.com:5443/mongo:5.0.15-focal
    container_name: router-01
    ports:
      - 27116:27017
    restart: always
    volumes:
      - /rit/smongo/1role/scripts:/scripts:ro
      - /rit/smongo/1role/route_1_data/db:/data/db:rw
      - /rit/smongo/1role/route_1_data/configdb:/data/configdb:rw
    command: mongos --port 27017 --configdb rs-config-server/10.122.0.2:27119,10.122.0.2:27120 --bind_ip_all --keyFile /dcs/mongodb-keyfile
