## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  ffmpeg:
    container_name: ffmpeg
    image: registry.roleit.com:5443/restffmpeg-pro:170423.200524
    restart: always #always #unless-stopped
    ports:
      - 20060:20060
    volumes:
      - /rit/env/ffmpeg.env:/restffmpeg/.env:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:20060/healthcheck || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      role:
        ipv4_address: 192.168.1.9
networks:
  role:
    external: true

# docker-compose -f 1-ffmpeg-dc.yaml up -d
# docker-compose -f 1-ffmpeg-dc.yaml down
