## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  graphql:
    container_name: graphql
    image: registry.roleit.com:5443/graphql-pro:170623.004813
    restart: always #on-failure #always
    ports:
      - 19784:19784
    volumes:
      - /rit/env/graphql.env:/graphql/.env:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:19784/graphql/healthcheck || exit 1"]
    #   # test: "curl -fsw '%{http_code}\n' --output /dev/null http://127.0.0.1:19784/graphql/healthcheck"
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    networks:
      role:
        ipv4_address: 192.168.1.6
networks:
  role:
    external: true

# docker-compose -f 1-graphql-dc.yaml up -d
# docker-compose -f 1-graphql-dc.yaml down

