## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  restml:
    image: registry.roleit.com:5443/alpyimages-pro:170423.190630
    restart: always
    container_name: restml
    ports:
      - 20070:20070
    volumes:
      - /rit/env/setting.py:/roleitPyImagesAL/projectConfig/settings.py:ro
    command: ["python3", "manage.py", "runserver", "0.0.0.0:20070"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:20070/healthcheck || exit 1"]
    #   # test: "curl -fsw '%{http_code}\n' --output /dev/null http://127.0.0.1:20070/healthcheck"
    #   # test: "wget --quiet --tries=1 --spider http://127.0.0.1:20070/healthcheck; echo $?"
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      role:
        ipv4_address: 192.168.1.10
networks:
  role:
    external: true

# docker-compose -f 10-restml-dc.yaml up -d
# docker-compose -f 10-restml-dc.yaml down
