## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  vidcommid:
    container_name: vidcommid
    image: registry.roleit.com:5443/program-vidcom-mid:130523.101942
    restart: always
    ports:
      - 44445:1191
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:20070/healthcheck || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      role:
        ipv4_address: 192.168.1.16
networks:
  role:
    external: true

# docker-compose -f 16-vidcom-mid-dc.yaml up -d
# docker-compose -f 16-vidcom-mid-dc.yaml down
