## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  vidcomlow:
    container_name: vidcomlow
    image: registry.roleit.com:5443/program-vidcom-low:130523.103556
    restart: always
    ports:
      - 44446:1192
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:20070/healthcheck || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      role:
        ipv4_address: 192.168.1.17
networks:
  role:
    external: true

# docker-compose -f 17-vidcom-low-dc.yaml up -d
# docker-compose -f 17-vidcom-low-dc.yaml down
