## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  vidcomsilent:
    container_name: vidcomsilent
    image: registry.roleit.com:5443/program-vidcom-silent:130523.103857
    restart: always
    ports:
      - 44447:1193
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:20070/healthcheck || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      role:
        ipv4_address: 192.168.1.18
networks:
  role:
    external: true

# docker-compose -f 18-vidcom-silent-dc.yaml up -d
# docker-compose -f 18-vidcom-silent-dc.yaml down
