## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  rest:
    container_name: rest
    image: registry.roleit.com:5443/restapi-pro:010723.151153
    restart: always #always #on-failure #always
    ports:
      - 19785:19785
    volumes:
      - /rit/env/rest.env:/roitrestapi/.env:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:19785/rest/healthcheck || exit 1"]
    #   # test: "curl -fsw '%{http_code}\n' --output /dev/null http://127.0.0.1:19785/rest/healthcheck"
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    networks:
      role:
        ipv4_address: 192.168.1.7
networks:
  role:
    external: true

# docker-compose -f 2-rest-dc.yaml up -d
# docker-compose -f 2-rest-dc.yaml down
