## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3'
services:
  socket:
    container_name: socket
    image: registry.roleit.com:5443/chatsocket-pro:100623.110933
    restart: always #on-failure #always
    ports:
      - 19786:19786
    volumes:
      - /rit/env/socket.env:/socket/.env:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:19786/healthcheck || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      role:
        ipv4_address: 192.168.1.8
networks:
  role:
    external: true

# docker-compose -f 3-socket-dc.yaml up -d
# docker-compose -f 3-socket-dc.yaml down

# docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redis

