# docker network create --driver=bridge --driver=bridge --subnet=192.168.1.0/16 role

version: '3'
services:
  nginx:
    # image: bitnami/nginx:1.23
    image: registry.roleit.com:5443/nginx:100
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /rit/nginx/config:/etc/nginx/conf.d:rw
      - /rit/nginx/1role/nginx.conf:/etc/nginx/nginx.conf:ro
      - /rit/nginx/cert:/etc/nginx/ssl:rw
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://10.0.101.155/index.html"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    networks:
      role:
        ipv4_address: 192.168.1.1
networks:
  role:
    external: true

# docker-compose docker-compose up -d
# docker-compose docker-compose down

#### my-images ####
# docker tag bitnami/nginx:1.23 dcsurani/bitnaminginx:1.23
# docker push dcsurani/bitnaminginx:1.23