## Diocker delete all images
# for /F %i in ('docker images -a -q') do docker rmi -f %i
# docker rmi -f $(docker images -a -q)

version: '3.3'
services:
  cassandra2:
    image: cassandra:4.1.0
    restart: on-failure #always
    container_name: cassandra-2
    # volumes:
    #   - $PWD:/var/lib/cassandra:rw
    environment:
      CASSANDRA_CLUSTER_NAME: hello
      CASSANDRA_SEEDS: 172.20.0.2
    ports:
      - 9043:9042
    networks:
      - roleit
        # ipv4_address: 172.19.0.12
networks:
  roleit:
    driver: bridge
    external: true

# docker-compose -f 1-graphql-dc.yaml up -d
# docker-compose -f 1-graphql-dc.yaml down